[package]
name = "rssh"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE-0BSD.txt"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
